version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Монтируем конфигурации для разработки (чтобы не пересобирать образ)
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./html/:/usr/share/nginx/html/:ro
      - ./ssl/:/etc/nginx/ssl/:ro
      - ./logs/:/var/log/nginx/
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - web-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Дополнительный сервис для примера с PHP
#  php-fpm:
#    image: php:7.4-fpm
#    container_name: php83-fpm
#    restart: unless-stopped
#    volumes:
#      - ./html/:/usr/share/nginx/html/
#    networks:
#      - web-network
#
#networks:
#  web-network:
#    driver: bridge

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php-83-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

networks:
  web-network:
    driver: bridge